<?php include 'inc/header.php'; ?>



    <!-- CONFERENCE INFO START -->

            <div class="container mywrapper">
              <div class="row">
                <div class="col-lg-12 col-md-12 col-xxl-12 col-12 ">
                  <h2 class="text-center">Organizing committee</h2>
                  <div class="reg-content">
                
                  <p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;'><strong><span style="font-size: 15px; color: black; font-family: Calibri, sans-serif;">Organizing Chair:&nbsp;</span></strong></p>
<p style='margin-right:0in;margin-left:.65in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Partha Chakraborty HOD, Department of Computer Science and Engineering, Comilla &nbsp; University, Cumilla</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><strong><span style="font-size:15px;color:black;">Organizing Co-Chair:</span></strong><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:43.8pt;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Khairun Nahar Department of Computer Science and Engineering, Comilla University, &nbsp; &nbsp;Cumilla&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:43.8pt;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Md. Khalil Ahammad Department of Computer Science and Engineering, Comilla University, Cumilla&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:43.8pt;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Md. Mohibullah Department of Computer Science and Engineering, Comilla University, Cumilla</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:7.8pt;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-indent:.5in;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Meskat Jahan Department of Computer Science and Engineering, Comilla University, Cumilla&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><strong><span style="font-size:15px;color:black;">Organizing Committee:</span></strong><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:.5in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Md. Zakir Hossain Department of Computer Science and Engineering, Comilla University, Cumilla</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-indent:.5in;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Khairun Nahar Department of Computer Science and Engineering, Comilla University, Cumilla</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:.5in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Md. Khalil Ahammad Department of Computer Science and Engineering, Comilla University, Cumilla</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:.5in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Chowdhury Shahriar Muzammel Department of Computer Science and Engineering, Comilla University, Cumilla</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-indent:.5in;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Md. Mohibullah Department of Computer Science and Engineering, Comilla University, Cumilla&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:.5in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Mahmuda Khatun Department of Computer Science and Engineering, Comilla University, Cumilla&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-indent:.5in;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Nayan Banik Department of Computer Science and Engineering, Comilla University, Cumilla&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-indent:.5in;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Meskat Jahan Department of Computer Science and Engineering, Comilla University, Cumilla&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-indent:.5in;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Aditi Sarker Department of Computer Science and Engineering, Comilla University, Cumilla</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;'><span style="font-family: Calibri, sans-serif;"><strong><span style="font-size:15px;color:black;">Publicity and Sponsorship Chair (Local):</span></strong></span></p>
<p style='margin-right:0in;margin-left:.5in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-indent:2.4pt;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Chowdhury Shahriar Muzammel Department of Computer Science and Engineering, Comilla University, Cumilla&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-indent:.5in;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Nayan Banik Department of Computer Science and Engineering, Comilla University, Cumilla&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><strong><span style="font-size:15px;color:black;">Web Chair:&nbsp;</span></strong></span></p>
<p style='margin-right:0in;margin-left:.5in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">Mahmuda Khatun Department of Computer Science and Engineering, Comilla University, Cumilla</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;text-align:start;'><span style="font-family: Calibri, sans-serif;"><span style="font-size:15px;color:black;">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Aditi Sarker Department of Computer Science and Engineering, Comilla University, Cumilla</span></span></p>
<p style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Siyam Rupali ANSI";margin-top:0in;margin-bottom:8.0pt;line-height:107%;'><span style="line-height: 107%; font-family: Calibri, sans-serif;">&nbsp;</span></p>



                 </div>
                </div>
              </div>
            </div>
  

     <!-- CONFERENCE INFO END -->


<?php include 'inc/footer.php'; ?>